#!/usr/bin/env bash
#installation guide for nginx

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw 'Nginx HTTP'

echo 'Hello World!' > /var/www/html/index.nginx-debian.html

#testing nginx configuration
sudo nginx -t

sudo service nginx restart
