#!/usr/bin/env bash
#installation guide for nginx

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World! | sudo tee /var/www/html/index.html"
printf %s "server {
    listen 80;
    listen [::]:80;
    root   /var/www/html;
    index  index.html;
}" > /etc/nginx/sites-available/default


#testing nginx configuration
sudo nginx -t

sudo service nginx restart
