#!/usr/bin/env bash

sudo pt-get update
sudo apt-get install nginx -y

echo "Hello world" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
printf %s "server {
    listen 80;
    listen [::]:80;
    root   /var/www/html;
    index  index.html;

    location /redirect_me {
        return 301 https://intranet.alxswe.com/users/my_profile;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
