#!/usr/bin/env bash
# This script displays'To infinity and beyond' indefinitely
# +and adds sleep 2 in between each iteration of the loop

while true;
do
	echo "To infinity and beyond";
	sleep 2
done
