#!/usr/bin/env bash
# This script displays "Best School" 10 times, using the while loop
# +but after the 9th iteration, displays Hi on a new line.

i=1
while ((i <= 10))
do
	echo "Best School"
	if ((i == 9))
	then
		echo 'Hi'
	fi
	((i++))
done
