#!/usr/bin/env bash
# using the while loop, display the time for 12 hours and 59 minutes:
# displaying hours from 0 to 12, and 
# displaying  minutes from 1 to 59.

hour=0
while ((hour < 13))
do
	echo "Hour: $hour"
	minute=1
	while ((minute < 60))
	do
		echo $minute
		((minute++))
	done
	((hour++))
done
