#!/usr/bin/env bash
# This bash script configures an Ubuntu server that:
# resolves localhost to '127.0.0.2'.
# and facebook.com to '8.8.8.8'.

cp /etc/hosts ~/hosts.new
sed -i "s/^127[0-9.]*\slocalhost/127.0.0.2 localhost/" ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
